version: "3.7"
services:
 app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: larakolos
    container_name: larakolos-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lara_net

 pgsql:
    image: 'postgres:14'
    container_name: larakolos-pgsql
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - './pg_data:/var/lib/postgresql/data'
#     - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - lara_net

 nginx:
    image: nginx:alpine
    container_name: larakolos-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lara_net

# npm:
#    image: node:current-alpine
#    volumes:
#      - ./src:/var/www/html
#    ports:
#      - "3000:3000"
#      - "3001:3001"
#      - "5173:5173"
#    working_dir: /var/www/html
#    entrypoint: [ 'npm' ]
#    networks:
#      - lara_net

networks:
  lara_net:
    driver: bridge
